version: "3.9"

services:
  seminar:
    container_name: colloquia
    build:
      context: .
    networks:
      - local
    ports:
      - "4000:4000"
    volumes:
      - .:/home

networks:
  local:
    name: local
